### ISSUE TITLE
Submit the issue to wpvulndb.com

### ISSUE THREAD

**Issue by madonius** [w4fz5uck5/wp-file-manager-0day#1]
It would be a good Idea to submit this issue on wpvulndb as the community should be made aware.

**Comment by DanielRuf** [comment]
Already happened so I guess this can be closed ;-)

**Comment by DanielRuf** [comment]
Already happened (I guess you already saw it) so I guess this issue can be closed ;-)
Also anyone can contact them (the WPScan team which maintains wpvulndb) and report such findings.

https://wpvulndb.com/vulnerabilities/10389

**Comment by madonius** [comment]
You're right ^^
I did not want to steal the credit for submission

**Comment by DanielRuf** [comment]
That's not a problem. They have updated the initial version of the report with more references in the URL section.

But the exact timeline is not clear to me - there may have been multiple reports.

**Comment by DanielRuf** [comment]
I doubt that the owner of this repository is interested to report this to the right persons ;-)

**Comment by w4fz5uck5** [comment]
> 
> 
> I doubt that the owner of this repository is interested to report this to the right persons ;-)

https://twitter.com/w4fz5uck5/status/1303396627198152707

**Comment by w4fz5uck5** [comment]
> 
> 
> You're right ^^
> I did not want to steal the credit for submission

sorry for the delay, for me it's not a problem.

**Comment by w4fz5uck5** [comment]
> 
> 
> > You're right ^^
> > I did not want to steal the credit for submission
> 
> sorry for the delay, for me it's not a problem.

My only request is for anyone who publish this vulnerability, link this repo as credit.

**Comment by w4fz5uck5** [comment]
Closing issue...

**Comment by DanielRuf** [comment]
> My only request is for anyone who publish this vulnerability, link this repo as credit.

Reopening is not needed. I'll contact the WPScan team to let them know so you get the credit too =)

**Comment by DanielRuf** [comment]
> > I doubt that the owner of this repository is interested to report this to the right persons ;-)
> 
> [twitter.com/w4fz5uck5/status/1303396627198152707](https://twitter.com/w4fz5uck5/status/1303396627198152707)

Sorry if I misinterpreted your intentions. So far I had the best experience with the WPScan team behind wpvulndb.com which can handle such things and also helped with coordinating this. It's definitely frustrating when the authors of the affected software do not answer (in the expected way), I know that too well.

I had the same problem that a vendor did not answer so they contacted them and got the needed information and kept me updated regarding my submission. I'm not sure if there are rules like some timeline regarding th disclosure on this website.

https://wpvulndb.com/submits/new

**Comment by w4fz5uck5** [comment]
Oh thanks friend! :) 
I'll try to contact wpvulndb today. Also, at now i'm very busy with another projects, which turned me out of this topic for some days.

**Comment by DanielRuf** [comment]
I already did and they added the link to your tweet.
